runtime: nodejs20

env_variables:
  NODE_ENV: production
  PORT: 8080
  
  # MongoDB Atlas Configuration
  # REPLACE THIS with your actual MongoDB connection string
  MONGODB_URI: "mongodb+srv://YOUR_USERNAME:YOUR_PASSWORD@YOUR_CLUSTER.mongodb.net/safestep?retryWrites=true&w=majority"
  DB_NAME: "NYC_Crashes"
  COLL_NAME: "NYC_Crash_Data"
  
  # OpenAI Configuration
  # REPLACE THIS with your actual OpenAI API key
  OPENAI_API_KEY: "sk-your-actual-openai-api-key-here"
  
  # Google Cloud Configuration
  # REPLACE THIS with your actual Google Cloud API key
  GOOGLE_CLOUD_API_KEY: "your-actual-google-cloud-api-key-here"

automatic_scaling:
  min_instances: 0
  max_instances: 10
  target_cpu_utilization: 0.6

resources:
  cpu: 1
  memory_gb: 2
  disk_size_gb: 10

handlers:
- url: /.*
  script: auto
  secure: always