steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/safestep:$COMMIT_SHA', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/safestep:$COMMIT_SHA']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'safestep'
      - '--image'
      - 'gcr.io/$PROJECT_ID/safestep:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--max-instances'
      - '10'
      - '--set-env-vars'
      - 'NODE_ENV=production,MONGODB_URI=mongodb+srv://YOUR_USERNAME:YOUR_PASSWORD@YOUR_CLUSTER.mongodb.net/safestep,OPENAI_API_KEY=sk-your-actual-key,GOOGLE_CLOUD_API_KEY=your-actual-key,DB_NAME=NYC_Crashes,COLL_NAME=NYC_Crash_Data'

images:
  - 'gcr.io/$PROJECT_ID/safestep:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY