// Sample NYC Motor Vehicle Collision Data for SafeStep Demo
export const sampleCrashData = [
  {
    crash_date: "2023-12-01",
    crash_time: "08:30",
    borough: "MANHATTAN",
    on_street_name: "BROADWAY",
    cross_street_name: "42 STREET",
    latitude: 40.7580,
    longitude: -73.9855,
    number_of_persons_injured: 1,
    number_of_persons_killed: 0,
    vehicle_type_code1: "SEDAN",
    vehicle_type_code2: "TAXI",
    contributing_factor_vehicle_1: "DRIVER INATTENTION/DISTRACTION",
    contributing_factor_vehicle_2: "UNSPECIFIED"
  },
  {
    crash_date: "2023-12-02",
    crash_time: "17:45",
    borough: "MANHATTAN",
    on_street_name: "5 AVENUE",
    cross_street_name: "59 STREET",
    latitude: 40.7647,
    longitude: -73.9730,
    number_of_persons_injured: 0,
    number_of_persons_killed: 1,
    vehicle_type_code1: "SPORT UTILITY / STATION WAGON",
    vehicle_type_code2: "BICYCLE",
    contributing_factor_vehicle_1: "FAILURE TO YIELD RIGHT-OF-WAY",
    contributing_factor_vehicle_2: "UNSPECIFIED"
  },
  {
    crash_date: "2023-12-03",
    crash_time: "12:15",
    borough: "MANHATTAN",
    on_street_name: "WEST SIDE HIGHWAY",
    cross_street_name: "14 STREET",
    latitude: 40.7398,
    longitude: -74.0080,
    number_of_persons_injured: 3,
    number_of_persons_killed: 0,
    vehicle_type_code1: "SEDAN",
    vehicle_type_code2: "PICK-UP TRUCK",
    contributing_factor_vehicle_1: "FOLLOWING TOO CLOSELY",
    contributing_factor_vehicle_2: "UNSPECIFIED"
  },
  {
    crash_date: "2023-12-04",
    crash_time: "22:30",
    borough: "BROOKLYN",
    on_street_name: "FLATBUSH AVENUE",
    cross_street_name: "ATLANTIC AVENUE",
    latitude: 40.6838,
    longitude: -73.9760,
    number_of_persons_injured: 2,
    number_of_persons_killed: 0,
    vehicle_type_code1: "SEDAN",
    vehicle_type_code2: "MOTORCYCLE",
    contributing_factor_vehicle_1: "ALCOHOL INVOLVEMENT",
    contributing_factor_vehicle_2: "UNSPECIFIED"
  },
  {
    crash_date: "2023-12-05",
    crash_time: "06:45",
    borough: "MANHATTAN",
    on_street_name: "FDR DRIVE",
    cross_street_name: "HOUSTON STREET",
    latitude: 40.7209,
    longitude: -73.9756,
    number_of_persons_injured: 1,
    number_of_persons_killed: 0,
    vehicle_type_code1: "SEDAN",
    vehicle_type_code2: "TRUCK",
    contributing_factor_vehicle_1: "UNSAFE SPEED",
    contributing_factor_vehicle_2: "UNSPECIFIED"
  },
  {
    crash_date: "2023-12-06",
    crash_time: "16:20",
    borough: "MANHATTAN",
    on_street_name: "PARK AVENUE",
    cross_street_name: "86 STREET",
    latitude: 40.7794,
    longitude: -73.9632,
    number_of_persons_injured: 0,
    number_of_persons_killed: 0,
    vehicle_type_code1: "TAXI",
    vehicle_type_code2: "SEDAN",
    contributing_factor_vehicle_1: "TRAFFIC CONTROL DISREGARDED",
    contributing_factor_vehicle_2: "UNSPECIFIED"
  },
  {
    crash_date: "2023-12-07",
    crash_time: "11:10",
    borough: "BROOKLYN",
    on_street_name: "BROOKLYN BRIDGE",
    cross_street_name: "ADAMS STREET",
    latitude: 40.7061,
    longitude: -73.9969,
    number_of_persons_injured: 4,
    number_of_persons_killed: 0,
    vehicle_type_code1: "BUS",
    vehicle_type_code2: "SEDAN",
    contributing_factor_vehicle_1: "DRIVER INEXPERIENCE",
    contributing_factor_vehicle_2: "UNSPECIFIED"
  },
  {
    crash_date: "2023-12-08",
    crash_time: "19:55",
    borough: "MANHATTAN",
    on_street_name: "LEXINGTON AVENUE",
    cross_street_name: "125 STREET",
    latitude: 40.8044,
    longitude: -73.9382,
    number_of_persons_injured: 1,
    number_of_persons_killed: 0,
    vehicle_type_code1: "SEDAN",
    vehicle_type_code2: "PEDESTRIAN",
    contributing_factor_vehicle_1: "FAILURE TO YIELD RIGHT-OF-WAY",
    contributing_factor_vehicle_2: "UNSPECIFIED"
  },
  {
    crash_date: "2023-12-09",
    crash_time: "13:40",
    borough: "MANHATTAN",
    on_street_name: "AMSTERDAM AVENUE",
    cross_street_name: "96 STREET",
    latitude: 40.7947,
    longitude: -73.9667,
    number_of_persons_injured: 0,
    number_of_persons_killed: 0,
    vehicle_type_code1: "BICYCLE",
    vehicle_type_code2: "TAXI",
    contributing_factor_vehicle_1: "OTHER VEHICULAR",
    contributing_factor_vehicle_2: "UNSPECIFIED"
  },
  {
    crash_date: "2023-12-10",
    crash_time: "09:25",
    borough: "MANHATTAN",
    on_street_name: "MADISON AVENUE",
    cross_street_name: "72 STREET",
    latitude: 40.7711,
    longitude: -73.9674,
    number_of_persons_injured: 2,
    number_of_persons_killed: 0,
    vehicle_type_code1: "SPORT UTILITY / STATION WAGON",
    vehicle_type_code2: "SEDAN",
    contributing_factor_vehicle_1: "BACKING UNSAFELY",
    contributing_factor_vehicle_2: "UNSPECIFIED"
  }
];